version: "3.8"

services:
  frontend:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - LOG_PATH=/app/logs/app.log
      - LOG_LEVEL=INFO
      - SERVICE_NAME=frontend
      - API_URL=http://api-service:9000
    env_file: .env
    volumes:
      - ../logs:/app/logs
    depends_on:
      - api-service
    networks:
      - app-network

  api-service:
    build:
      context: ../api-service
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    env_file: .env
    networks:
      - app-network

  worker:
    build:
      context: ../worker
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - API_URL=http://api-service:9000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
